name: Rust

on:
  push:
    branches: [ "main" , "*-dev"]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: BuildWindows
      run: |
        rustup target add x86_64-pc-windows-gnu
        cargo build --target x86_64-pc-windows-gnu --verbose
    - name: Run tests
      run: cargo test --verbose
